import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
const cli = path.join(root, 'node_modules/supabase/dist/supabase.js');

export function runCli(args, capture = false) {
  const result = spawnSync(process.execPath, [cli, ...args], {
    cwd: root, encoding: 'utf8', stdio: capture ? 'pipe' : 'inherit',
  });
  if (result.error || result.status !== 0) {
    throw new Error(capture
      ? 'Local Supabase is unavailable. Run npm run supabase:start first.'
      : `Supabase command failed (exit ${result.status ?? 'unknown'}).`);
  }
  return result.stdout;
}

export function localEnvironment(output) {
  const values = Object.fromEntries(output.split(/\r?\n/).flatMap((line) => {
    const match = line.match(/^([A-Z_]+)="(.*)"$/);
    return match ? [[match[1], match[2]]] : [];
  }));
  const api = new URL(values.API_URL);
  if (api.protocol !== 'http:' || !['localhost', '127.0.0.1', '[::1]'].includes(api.hostname)) {
    throw new Error('Refusing to use a non-loopback Supabase URL for local development.');
  }
  if (!values.ANON_KEY) throw new Error('Local Supabase status did not return an anon key.');
  return {
    NEXT_PUBLIC_SITE_URL: 'http://localhost:3001',
    NEXT_PUBLIC_SUPABASE_URL: api.origin,
    NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: values.ANON_KEY,
    // Override any inherited cloud service key. Never expose this in NEXT_PUBLIC_*.
    SUPABASE_SERVICE_ROLE_KEY: values.SERVICE_ROLE_KEY || '',
  };
}

export function getLocalEnvironment() {
  return localEnvironment(runCli(['status', '-o', 'env'], true));
}

function main() {
  const [action, ...extra] = process.argv.slice(2);
  // No forwarded flags: --linked, --db-url, --project-ref and --workdir cannot
  // change the target of these convenience commands.
  if (extra.length) throw new Error('Local scripts do not accept additional arguments.');
  const commands = {
    start: ['start'], stop: ['stop'], reset: ['db', 'reset', '--local'], status: ['status'],
  };
  if (commands[action]) return runCli(commands[action]);
  if (!['env', 'dev', 'build'].includes(action)) throw new Error('Unknown local command.');

  const environment = getLocalEnvironment();
  if (action === 'env') {
    const target = path.join(root, '.env.development.local');
    const marker = '# Generated by npm run supabase:env; local Docker credentials only.';
    if (existsSync(target) && !readFileSync(target, 'utf8').startsWith(marker)) {
      throw new Error('Existing .env.development.local is not generated; preserve or move it manually first.');
    }
    writeFileSync(target, `${marker}\n${Object.entries(environment).map(([key, value]) => `${key}=${JSON.stringify(value)}`).join('\n')}\n`, { mode: 0o600 });
    console.log('Wrote ignored .env.development.local. Existing .env.local was preserved.');
    return;
  }
  console.log(`Using local Supabase at ${environment.NEXT_PUBLIC_SUPABASE_URL}`);
  const next = path.join(root, 'node_modules/next/dist/bin/next');
  const result = spawnSync(process.execPath, [next, action === 'dev' ? 'dev' : 'build',
    ...(action === 'dev' ? ['--hostname', 'localhost', '--port', '3001'] : [])], {
    cwd: root, stdio: 'inherit', env: { ...process.env, ...environment },
  });
  if (result.error) throw result.error;
  process.exitCode = result.status ?? 1;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try { main(); } catch (error) { console.error(error.message); process.exitCode = 1; }
}
