import type { EventItem, Facility, NotificationItem, PartnerRequest, PlayerGroup, PlayerProfile, SetScore, Team, TournamentGroup, FeedbackItem } from '../types';

export interface PadelContextValue {
  currentUser: PlayerProfile;
  allPlayers: PlayerProfile[];
  facilities: Facility[];
  events: EventItem[];
  playerGroups: PlayerGroup[];
  notifications: NotificationItem[];
  clearNotifications: () => void;
  partnerRequests: PartnerRequest[];
  isAppAdmin: boolean;
  planNotice: string;
  clearPlanNotice: () => void;
  submitFeedback: (data: { type: FeedbackItem['type']; title: string; description: string; pageRoute?: string; contactConsent: boolean }) => Promise<{ success: boolean; error?: string }>;
  fetchFeedback: (scope: 'mine' | 'all') => Promise<FeedbackItem[]>;
  updateFeedbackStatus: (feedbackId: string, status: FeedbackItem['status']) => Promise<boolean>;
  signUpAction: (data: { firstName: string; lastName: string; email: string; password: string }) => Promise<{ success: boolean; error?: string }>;
  loginAction: (email: string, password: string) => Promise<{ success: boolean; error?: string }>;
  logoutAction: () => Promise<void>;
  forgotPasswordAction: (email: string) => Promise<{ success: boolean; error?: string }>;
  resetPasswordAction: (password: string) => Promise<{ success: boolean; error?: string }>;
  isAuthenticated: boolean;
  switchUser: (userId: string) => void;
  loginUser: (email: string) => boolean;
  registerUser: (firstName: string, lastName: string, email: string, mobile?: string) => void;
  createEvent: (newEventData: Partial<EventItem>) => Promise<string>;
  updateEvent: (eventId: string, changes: Pick<EventItem, 'name' | 'description' | 'format' | 'date' | 'startTime' | 'visibility' | 'maxPlayers'>) => Promise<void>;
  deleteEvent: (eventId: string) => Promise<boolean>;
  joinEvent: (eventId: string, preferredPartnerId?: string) => Promise<{ success: boolean; status?: 'confirmed' | 'waiting_list' }>;
  leaveEvent: (eventId: string, targetUserId?: string) => void;
  removeParticipant: (eventId: string, targetUserId: string) => void;
  addRegisteredPlayerToEvent: (eventId: string, userId: string) => Promise<boolean>;
  addGuestPlayer: (eventId: string, guestName: string) => Promise<boolean>;
  removeGuestPlayer: (eventId: string, guestId: string) => void;
  sendPartnerRequest: (eventId: string, toUserId: string) => void;
  respondToPartnerRequest: (requestId: string, accept: boolean) => void;
  generateTeams: (eventId: string) => void;
  updateTeams: (eventId: string, teams: Team[]) => void;
  generateEventGroupsAction: (eventId: string) => void;
  updateGroups: (eventId: string, groups: TournamentGroup[]) => void;
  generateEventScheduleAction: (eventId: string) => void;
  recordMatchScoreAction: (eventId: string, matchId: string, team1Score: number, team2Score: number, sets?: SetScore[]) => void;
  confirmQualifiersAndKnockout: (eventId: string) => void;
  addCoAdmin: (eventId: string, userId: string) => void;
  removeCoAdmin: (eventId: string, userId: string) => void;
  createPlayerGroupAction: (name: string, description: string, memberIds: string[]) => Promise<PlayerGroup>;
  deletePlayerGroupAction: (groupId: string) => Promise<boolean>;
  joinPlayerGroupAction: (groupId: string, targetUserId?: string, initialGroupData?: Partial<PlayerGroup>) => Promise<void>;
  requestJoinPlayerGroupAction: (groupId: string, targetUserId?: string, initialGroupData?: Partial<PlayerGroup>) => void;
  approveGroupJoinRequestAction: (groupId: string, requestingUserId: string) => void;
  rejectGroupJoinRequestAction: (groupId: string, requestingUserId: string) => void;
  inviteGroupToEventAction: (eventId: string, groupId: string) => void;
  saveFacility: (data: Partial<Facility> & { name: string; address: string; city: string }) => Promise<Facility>;
  toggleFavoriteFacility: (facilityId: string) => void;
  deleteFacility: (facilityId: string) => void;
  resetDemoData: () => void;
  updateProfile: (data: Pick<PlayerProfile, 'displayName' | 'mobileNumber'>) => Promise<void>;
}
